#requires -Version 7.0
<#
.SYNOPSIS
    Aggregates ci-bench.ps1 JSON results from a matrix run into a single
    Markdown summary, and refreshes results/CI-RESULTS.md with the latest
    numbers. Called by the "publish" job in .github/workflows/ci-bench.yml
    after all matrix legs of a run have finished.

.PARAMETER RunId
    GitHub Actions run id the results came from (for linking/labeling).

.PARAMETER ResultsDir
    Directory containing the downloaded *.json result files for this run
    (one per matrix leg, named "<runner-label>.json").

.PARAMETER RepoRoot
    Root of the repo checkout (where results/CI-RESULTS.md lives).
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$RunId,
    [Parameter(Mandatory)][string]$ResultsDir,
    [string]$RepoRoot = (Get-Location)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$jsonFiles = Get-ChildItem -Path $ResultsDir -Filter '*.json' -Recurse
if (-not $jsonFiles) { throw "No *.json result files found under $ResultsDir" }

$rows = @()
foreach ($f in $jsonFiles) {
    $r = Get-Content $f.FullName -Raw | ConvertFrom-Json
    $rows += [pscustomobject]@{
        Runner       = $r.RunnerLabel
        Os           = $r.MachineSpec.Os
        OsVersion    = $r.MachineSpec.OsVersion
        Arch         = $r.MachineSpec.Architecture
        Cpu          = $r.MachineSpec.CpuModel
        LogicalCores = $r.MachineSpec.LogicalCores
        PhysCores    = $r.MachineSpec.PhysicalCores
        MemGB        = $r.MachineSpec.MemoryGB
        FreeDiskGB   = $r.MachineSpec.FreeDiskGB
        SpawnSec     = $r.Microbench.SpawnSeconds
        FileSec      = $r.Microbench.FileSeconds
        BuildSec     = $r.Build.BuildSeconds
        LitWallSec   = $r.Lit.WallSeconds
        LitPassFailTotal = "$($r.Lit.Pass)/$($r.Lit.Fail)/$($r.Lit.Total)"
        Commit       = $r.Commit
        Timestamp    = $r.Timestamp
    }
}
$rows = $rows | Sort-Object Runner

$lines = @()
$lines += "# CI perf-bench results"
$lines += ""
$lines += "Auto-generated by `.github/workflows/ci-bench.yml` (run [$RunId](https://github.com/$env:GITHUB_REPOSITORY/actions/runs/$RunId))."
$lines += "Produced by `ci-bench.ps1`, a self-contained single-machine variant of the main"
$lines += "Windows-vs-WSL benchmark - each row below is one GitHub-hosted runner type,"
$lines += "measured independently (no cross-machine ratio; compare rows directly instead)."
$lines += ""
$lines += "## Latest run: $($rows[0].Timestamp) UTC (LLVM @ $($rows[0].Commit))"
$lines += ""
$lines += "### Machine spec"
$lines += ""
$lines += "| Runner | OS | Arch | CPU | Logical cores | Physical cores | RAM (GB) | Free disk (GB) |"
$lines += "|---|---|---|---|---:|---:|---:|---:|"
foreach ($r in $rows) {
    $lines += "| $($r.Runner) | $($r.OsVersion) | $($r.Arch) | $($r.Cpu) | $($r.LogicalCores) | $($r.PhysCores) | $($r.MemGB) | $($r.FreeDiskGB) |"
}
$lines += ""
$lines += "### Results"
$lines += ""
$lines += "| Runner | Process spawn x200 (s) | File create+delete x2000 (s) | Build llvm-reduce+deps (s) | lit llvm-reduce wall (s) | lit pass/fail/total |"
$lines += "|---|---:|---:|---:|---:|---:|"
foreach ($r in $rows) {
    $lines += "| $($r.Runner) | $($r.SpawnSec) | $($r.FileSec) | $($r.BuildSec) | $($r.LitWallSec) | $($r.LitPassFailTotal) |"
}
$lines += ""
$lines += "Full per-runner machine-spec + result JSON/Markdown for this and every past run are kept under"
$lines += "``results/ci-runs/<run-id>/``, one file per runner label, so historical runs remain individually inspectable."

$outPath = Join-Path $RepoRoot 'results\CI-RESULTS.md'
$lines -join "`n" | Out-File -FilePath $outPath -Encoding utf8
Write-Host "Wrote $outPath"

# --- Keep README's CI section in sync with a short pointer + the latest results table ---
$readmePath = Join-Path $RepoRoot 'README.md'
$readme = Get-Content $readmePath -Raw
$startMarker = '<!-- CI-BENCH-RESULTS:START -->'
$endMarker = '<!-- CI-BENCH-RESULTS:END -->'

$section = @()
$section += $startMarker
$section += ""
$section += "### Results ($($rows[0].Timestamp) UTC, LLVM @ $($rows[0].Commit))"
$section += ""
$section += "| Runner | OS | Arch | CPU | Logical cores | RAM (GB) | Spawn x200 (s) | File x2000 (s) | Build (s) | lit wall (s) | lit P/F/Total |"
$section += "|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|"
foreach ($r in $rows) {
    $section += "| $($r.Runner) | $($r.OsVersion) | $($r.Arch) | $($r.Cpu) | $($r.LogicalCores) | $($r.MemGB) | $($r.SpawnSec) | $($r.FileSec) | $($r.BuildSec) | $($r.LitWallSec) | $($r.LitPassFailTotal) |"
}
$section += ""
$section += 'Full history: [`results/CI-RESULTS.md`](results/CI-RESULTS.md) and [`results/ci-runs/`](results/ci-runs/).'
$section += ""
$section += $endMarker
$sectionText = $section -join "`n"

$evaluator = [System.Text.RegularExpressions.MatchEvaluator] { param($m) $sectionText }
if ($readme -match [regex]::Escape($startMarker)) {
    $pattern = "(?s)$([regex]::Escape($startMarker)).*?$([regex]::Escape($endMarker))"
    $readme = [regex]::Replace($readme, $pattern, $evaluator)
}
else {
    $readme = $readme.TrimEnd() + "`n`n## CI perf-bench (GitHub-hosted runners)`n`nAutomated, self-contained runs of ``ci-bench.ps1`` via ``.github/workflows/ci-bench.yml``` on GitHub-hosted Windows x64, Windows ARM64, and Linux x64 runners - each runner benchmarked independently (no cross-machine ratio).`n`n$sectionText`n"
}
$readme | Out-File -FilePath $readmePath -Encoding utf8 -NoNewline
Write-Host "Updated $readmePath"
